    kind: pipeline
    name: default

    #platform:
    #  os: linux
    #  arch: arm64

    steps:
    - name: dockerize
      image: docker
      volumes:
      - name: dockersocket
        path: /var/run/docker.sock
      commands:
      - apk add debootstrap perl
      - cp . /
      - cd /
      - ./build.sh
      - echo "$DOCKER_PASSWORD" | docker login -u blafy --password-stdin
      - docker push blafy/raspbian


    volumes:
    - name: dockersocket
      host:
        path: /var/run/docker.sock

    trigger:
      event:
      - push
