    kind: pipeline
    name: default

    #platform:
    #  os: linux
    #  arch: arm64

    steps:
    - name: dockerize
      image: docker
      volumes:
      - name: dockersocket
        path: /var/run/docker.sock
      environment:
        DOCKER_PASSWORD:
          from_secret: dockerpwd
      commands:
      - apk add debootstrap perl
      - cp debootstrap.sh /
      - cd /
      - ./debootstrap.sh
      - cd /drone/src
      - ./build.sh
      - export DOCKER_CLI_EXPERIMENTAL=enabled
      - echo $DOCKER_PASSWORD | docker login -u blafy --password-stdin
      - docker push blafy/raspbian
      - docker manifest create blafy/raspbian blafy/raspbian --arch arm --variant v6
      - docker push manifest blafy/raspbian
      - docker system prune -af


    volumes:
    - name: dockersocket
      host:
        path: /var/run/docker.sock

    trigger:
      event:
      - push
