    kind: pipeline
    name: default

    #platform:
    #  os: linux
    #  arch: arm64

    steps:
    - name: dockerize
      image: docker
      volumes:
      - name: dockersocket
        path: /var/run/docker.sock
      commands:
      - apk add debootstrap perl
      - cp debootstrap.sh /
      - cd /
      - ./debootstrap.sh
      - cd /drone/src
      - ./build.sh
      - echo "$DOCKER_PASSWORD" | docker login -u blafy --password-stdin
      - docker push blafy/raspbian
      - docker system prune -af


    volumes:
    - name: dockersocket
      host:
        path: /var/run/docker.sock

    trigger:
      event:
      - push
